routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if ( !auth()->user() )
        return view('general.index');
    else
        return redirect()->to( 'home' );
});


Route::group(['prefix' => '/umum'], function() {
    Route::get('/', 'SuratUmumController@index')->name('umum.index');

    Route::get('/domisili', 'SuratKeteranganDomisiliController@indexGuest')->name('domisili.index');
    Route::post('/domisili', 'SuratKeteranganDomisiliController@insertGuest')->name('domisili.insert');
    Route::get('/domisili/print/{id}', 'SuratKeteranganDomisiliController@print')->name('domisili.print');

    Route::get('/pajak', 'SuratKeteranganPajakController@indexGuest')->name('pajak.index');
    Route::post('/pajak', 'SuratKeteranganPajakController@insertGuest')->name('pajak.insert');
    Route::get('/pajak/print/{id}', 'SuratKeteranganPajakController@print')->name('pajak.print');

    Route::get('/kuasa', 'SuratKuasaTanahController@indexGuest')->name('kuasa.index');
    Route::post('/kuasa', 'SuratKuasaTanahController@insertGuest')->name('kuasa.insert');
    Route::get('/kuasa/print/{id}', 'SuratKuasaTanahController@print')->name('kuasa.print');
    
    Route::get('/imb', 'SuratRekomendasiImbController@indexGuest')->name('imb.index');
    Route::post('/imb', 'SuratRekomendasiImbController@insertGuest')->name('imb.insert');
    Route::get('/imb/print/{id}', 'SuratRekomendasiImbController@print')->name('imb.print');

    Route::get('/usaha', 'SuratKeteranganUsahaController@indexGuest')->name('usaha.index');
    Route::post('/usaha', 'SuratKeteranganUsahaController@insertGuest')->name('usaha.insert');
    Route::get('/usaha/print/{id}', 'SuratKeteranganUsahaController@print')->name('usaha.print');

});

Route::group(['prefix' => '/khusus'], function() {
    Route::get('/', 'SuratKhususController@index')->name('khusus.index');

    Route::get('/keramaian', 'SuratKeteranganIzinKeramaianController@indexGuest')->name('keramaian.index');
    Route::post('/keramaian', 'SuratKeteranganIzinKeramaianController@insertGuest')->name('keramaian.insert');
    Route::get('/keramaian/print/{id}', 'SuratKeteranganIzinKeramaianController@print')->name('keramaian.print');

    Route::get('/penghasilan', 'SuratKeteranganPenghasilanController@indexGuest')->name('penghasilan.index');
    Route::post('/penghasilan', 'SuratKeteranganPenghasilanController@insertGuest')->name('penghasilan.insert');
    Route::get('/penghasilan/print/{id}', 'SuratKeteranganPenghasilanController@print')->name('penghasilan.print');

    Route::get('/tidakMampu', 'SuratKeteranganTidakMampuController@indexGuest')->name('tidakMampu.index');
    Route::post('/tidakMampu', 'SuratKeteranganTidakMampuController@insertGuest')->name('tidakMampu.insert');
    Route::get('/tidakMampu/print/{id}', 'SuratKeteranganTidakMampuController@print')->name('tidakMampu.print');

    Route::get('/ahliWaris', 'SuratKeteranganAhliWarisController@indexGuest')->name('ahliWaris.index');
    Route::post('/ahliWaris', 'SuratKeteranganAhliWarisController@insertGuest')->name('ahliWaris.insert');
    Route::get('/ahliWaris/print/{id}', 'SuratKeteranganAhliWarisController@print')->name('ahliWaris.print');

    Route::get('/bedaNama', 'SuratKeteranganBedaNamaController@indexGuest')->name('bedaNama.index');
    Route::post('/bedaNama', 'SuratKeteranganBedaNamaController@insertGuest')->name('bedaNama.insert');
    Route::get('/bedaNama/print/{id}', 'SuratKeteranganBedaNamaController@print')->name('bedaNama.print');

    Route::get('/belumNpwp', 'SuratKeteranganBelumNpwpController@indexGuest')->name('belumNpwp.index');
    Route::post('/belumNpwp', 'SuratKeteranganBelumNpwpController@insertGuest')->name('belumNpwp.insert');
    Route::get('/belumNpwp/print/{id}', 'SuratKeteranganBelumNpwpController@print')->name('belumNpwp.print');

    Route::get('/hibah', 'SuratPernyataanHibahController@indexGuest')->name('hibah.index');
    Route::post('/hibah', 'SuratPernyataanHibahController@insertGuest')->name('hibah.insert');
    Route::get('/hibah/print/{id}', 'SuratPernyataanHibahController@print')->name('hibah.print');

    Route::get('/janda', 'SuratKeteranganJandaController@indexGuest')->name('janda.index');
    Route::post('/janda', 'SuratKeteranganJandaController@insertGuest')->name('janda.insert');
    Route::get('/janda/print/{id}', 'SuratKeteranganJandaController@print')->name('janda.print');

    Route::get('/belumMenikah', 'SuratBelumPernahMenikahController@indexGuest')->name('belumMenikah.index');
    Route::post('/belumMenikah', 'SuratBelumPernahMenikahController@insertGuest')->name('belumMenikah.insert');
    Route::get('/belumMenikah/print/{id}', 'SuratBelumPernahMenikahController@print')->name('belumMenikah.print');

    Route::get('/hubunganKeluarga', 'SuratKeteranganHubunganKeluargaController@indexGuest')->name('hubunganKeluarga.index');
    Route::post('/hubunganKeluarga', 'SuratKeteranganHubunganKeluargaController@insertGuest')->name('hubunganKeluarga.insert');
    Route::get('/hubunganKeluarga/print/{id}', 'SuratKeteranganHubunganKeluargaController@print')->name('hubunganKeluarga.print');

    Route::get('/PanggilanCerai', 'SuratKeteranganPanggilanCeraiController@indexGuest')->name('PanggilanCerai.index');
    Route::post('/PanggilanCerai', 'SuratKeteranganPanggilanCeraiController@insertGuest')->name('PanggilanCerai.insert');
    Route::get('/PanggilanCerai/print/{id}', 'SuratKeteranganPanggilanCeraiController@print')->name('PanggilanCerai.print');

    Route::get('/keterangan', 'SuratKeteranganController@indexGuest')->name('keterangan.index');
    Route::post('/keterangan', 'SuratKeteranganController@insertGuest')->name('keterangan.insert');
    Route::get('/keterangan/print/{id}', 'SuratKeteranganController@print')->name('keterangan.print');

    Route::get('/keteranganKematian', 'SuratKeteranganTentangKematianController@indexGuest')->name('keteranganKematian.index');
    Route::post('/keteranganKematian', 'SuratKeteranganTentangKematianController@insertGuest')->name('keteranganKematian.insert');
    Route::get('/keteranganKematian/print/{id}', 'SuratKeteranganTentangKematianController@print')->name('keteranganKematian.print');

    Route::get('/keteranganKelahiran', 'SuratKeteranganKelahiranController@indexGuest')->name('keteranganKelahiran.index');
    Route::post('/keteranganKelahiran', 'SuratKeteranganKelahiranController@insertGuest')->name('keteranganKelahiran.insert');
    Route::get('/keteranganKelahiran/print/{id}', 'SuratKeteranganKelahiranController@print')->name('keteranganKelahiran.print');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home.index');
Route::get('/about', 'AboutController@index')->name('about.index');
Route::get('/dashboard/{name?}', 'DashboardController@index' )->name('dashboard.index');


Route::resource('preferences', 'PreferenceController')->only(['index', 'store']);
Route::patch('preferences/logo/update', 'PreferenceController@updateLogo')->name('preferences.update.logo');
Route::delete('preferences/logo/destroy', 'PreferenceController@destroyLogo')->name('preferences.destroy.logo');

Route::resource('users', 'UserController');
Route::patch('users/{user}/password/update', 'UserController@updatePassword')->name('users.update.password');

Route::resource('suratKeteranganDomisilis', 'SuratKeteranganDomisiliController');

Route::resource('suratKeteranganIzinKeramaians', 'SuratKeteranganIzinKeramaianController');

Route::resource('suratKeteranganPajaks', 'SuratKeteranganPajakController');

Route::resource('suratKeteranganPenghasilans', 'SuratKeteranganPenghasilanController');

Route::get('documents', 'DocumentController@index')->name('documents.index');


Route::resource('suratRekomendasiImbs', 'SuratRekomendasiImbController');

Route::resource('suratKeteranganUsahas', 'SuratKeteranganUsahaController');

Route::resource('suratKuasaTanahs', 'SuratKuasaTanahController');

Route::resource('suratKeteranganTidakMampus', 'SuratKeteranganTidakMampuController');

Route::resource('suratKeteranganAhliWaris', 'SuratKeteranganAhliWarisController');

Route::resource('ahliWarisKeterenganAhliWaris', 'AhliWarisKeterenganAhliWarisController');

Route::resource('saksiKeteranganAhliWaris', 'SaksiKeteranganAhliWarisController');

Route::resource('suratKeteranganBedaNamas', 'SuratKeteranganBedaNamaController');

Route::resource('suratKeteranganBelumNpwps', 'SuratKeteranganBelumNpwpController');

Route::resource('suratPernyataanHibahs', 'SuratPernyataanHibahController');

Route::resource('riwayatKepemilikanHibahs', 'RiwayatKepemilikanHibahController');

Route::resource('suratKeteranganJandas', 'SuratKeteranganJandaController');

Route::resource('suratBelumPernahMenikahs', 'SuratBelumPernahMenikahController');

Route::resource('suratKeteranganHubunganKeluargas', 'SuratKeteranganHubunganKeluargaController');

Route::resource('suratKeteranganPanggilanCerais', 'SuratKeteranganPanggilanCeraiController');

Route::resource('suratKeterangans', 'SuratKeteranganController');

Route::resource('suratKeteranganTentangKematians', 'SuratKeteranganTentangKematianController');

Route::resource('suratKeteranganKelahirans', 'SuratKeteranganKelahiranController');

app/Models/Preference.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Preference
 * @package App\Models
 * @version November 26, 2019, 9:18 am UTC
 *
 * @property string label
 * @property string value
 */
class Preference extends Model
{
    use SoftDeletes;

    public $table = 'preferences';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'label',
        'value'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'label' => 'string',
        'value' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'label' => 'required',
        'value' => 'required'
    ];

    public function scopeNamaDesa($query)
    {
        return $query->where('label','Desa')->first();
    }

    public function scopeLogo( $query )
    {
        return $query->where('label', 'Logo');
    }
}

app/Http/Controllers/PreferenceController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreatePreferenceRequest;
use App\Http\Requests\UpdatePreferenceRequest;
use App\Http\Requests\UpdateLogoRequest;
use App\Repositories\PreferenceRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

use App\Models\Preference;

class PreferenceController extends AppBaseController
{
    /** @var  PreferenceRepository */
    private $preferenceRepository;

    public function __construct(PreferenceRepository $preferenceRepo)
    {
        $this->preferenceRepository = $preferenceRepo;
        $this->middleware('auth');
    }

    /**
     * Display a listing of the Preference.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $preferences = Preference::get()->keyBy('label')->toArray();

        return view('preferences.index')
            ->with('preferences', $preferences);
    }

    public function store(Request $request)
    {
        $input = $request->except(['_token','submit']);
        foreach($input as $label => $value){
            $preference = Preference::where('label',str_replace("_"," ", $label))->first();

            $preference->value = $value;

            $preference->save();
        }

        $preferences = Preference::get()->keyBy('label')->toArray();
        Flash::success('Preference saved successfully.');
        return view('preferences.index')
            ->with('preferences', $preferences);
    }

    public function updateLogo(UpdateLogoRequest $request)
    {
        $publicPath = public_path('images/assets');
        $imageName = md5(date('Y-m-d H:i:s')) . '.' . $request->logo->getClientOriginalExtension();

        $request->logo->move($publicPath, $imageName);
        
        Preference::logo()->update([
            'value' => 'images/assets/' . $imageName,
        ]);

        Flash::success('Logo berhasil diperbaharui.');

        return redirect()->route('preferences.index');
    }

    public function destroyLogo()
    {
        Preference::logo()->update([
            'value' => '',
        ]);

        Flash::success('Logo berhasil dihapus.');

        return redirect()->route('preferences.index');
    }
}

resources/views/preferences/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Preference
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'preferences.store']) !!}

                        @include('preferences.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/preferences/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Preference
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($preference, ['route' => ['preferences.update', $preference->id], 'method' => 'patch']) !!}

                        @include('preferences.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/preferences/fields.blade.php
<!-- Label Field -->
<div class="form-group col-sm-6">
    {!! Form::label('label', 'Label:') !!}
    {!! Form::text('label', null, ['class' => 'form-control']) !!}
</div>

<!-- Value Field -->
<div class="form-group col-sm-6">
    {!! Form::label('value', 'Value:') !!}
    {!! Form::text('value', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('preferences.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/preferences/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>Preferensi</h1>
    </section>
    <br>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                <form action="{!! route('preferences.store') !!}" method="POST">
                    @csrf
                    <div class="form-group col-sm-6">
                        <label>Provinsi</label> 
                        <input type="text" name="Provinsi" id="Provinsi" class="form-control" value="{{$preferences['Provinsi']['value']}}">

                        <label>Kabupaten</label> 
                        <input type="text" name="Kabupaten" id="Kabupaten" class="form-control" value="{{$preferences['Kabupaten']['value']}}">

                        <label>Kecamatan</label> 
                        <input type="text" name="Kecamatan" id="Kecamatan" class="form-control" value="{{$preferences['Kecamatan']['value']}}">

                        <label>Desa</label> 
                        <input type="text" name="Desa" id="Desa" class="form-control" value="{{$preferences['Desa']['value']}}">

                        <label>Alamat</label> 
                        <input type="text" name="Alamat" id="Alamat" class="form-control" value="{{$preferences['Alamat']['value']}}">

                        <label>Kepala Desa</label> 
                        <input type="text" name="Kepala Desa" id="Kepala Desa" class="form-control" value="{{$preferences['Kepala Desa']['value']}}">
                    </div>
                    <div class="form-group col-sm-12">
                        <input type="submit" name="submit" class="btn btn-primary" value="Simpan Preferensi">
                        <a href="{!! route('preferences.index') !!}" class="btn btn-default">Batal</a>
                    </div>
                </form>    
            </div>
        </div>
    </div>

    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="box box-primary">
            <div class="box-body">
                <div class="col-sm-12">
                    <h3 class="box-title">Pengelolaan Logo Desa</h3>
                    {!! Form::open(['route' => 'preferences.update.logo', 'method' => 'patch', 'enctype' => 'multipart/form-data']) !!}

                        <div class="form-group">
                            {!! Form::label('', 'Logo saat ini') !!}
                            <br>
                            @if ( $preferences['Logo']['value'] == '' )
                            <img src="{{ asset('images/assets/placeholder.png') }}" width="300px">
                            @else
                            <img src="{{ asset($preferences['Logo']['value']) }}" width="300px">
                            @endif
                        </div>

                        <div class="form-group">
                            {!! Form::label('logo', 'Pilih Logo') !!}
                            {!! Form::file('logo') !!}
                        </div>

                        <div class="form-group">
                            {!! Form::submit('Simpan Logo', ['class' => 'btn btn-primary']) !!}
                            {!! Form::button('Hapus Logo', ['class' => 'btn btn-danger', 'onclick' => 'destroyLogo()']) !!}
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>

    {!! Form::open(['route' => 'preferences.destroy.logo', 'method' => 'delete', 'id' => 'form-destroy-logo']) !!}
    {!! Form::close() !!}
@endsection

@section( 'scripts' )
    <script type="text/javascript">
        function destroyLogo()
        {
            if ( confirm('Anda yakin akan menghapus logo?') )
            {
                $( '#form-destroy-logo' ).submit();
            }
        }
    </script>
@endsection

resources/views/preferences/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Preference
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('preferences.show_fields')
                    <a href="{!! route('preferences.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/preferences/show_fields.blade.php
<!-- Label Field -->
<div class="form-group">
    {!! Form::label('label', 'Label:') !!}
    <p>{!! $preference->label !!}</p>
</div>

<!-- Value Field -->
<div class="form-group">
    {!! Form::label('value', 'Value:') !!}
    <p>{!! $preference->value !!}</p>
</div>

resources/views/preferences/table.blade.php
<div class="table-responsive">
    <table class="table" id="preferences-table">
        <thead>
            <tr>
                <th>Label</th>
        <th>Value</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($preferences as $preference)
            <tr>
                <td>{!! $preference->label !!}</td>
            <td>{!! $preference->value !!}</td>
                <td>
                    {!! Form::open(['route' => ['preferences.destroy', $preference->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('preferences.show', [$preference->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{!! route('preferences.edit', [$preference->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>