routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if ( !auth()->user() )
        return view('general.index');
    else
        return redirect()->to( 'home' );
});


Route::group(['prefix' => '/umum'], function() {
    Route::get('/', 'SuratUmumController@index')->name('umum.index');

    Route::get('/domisili', 'SuratKeteranganDomisiliController@indexGuest')->name('domisili.index');
    Route::post('/domisili', 'SuratKeteranganDomisiliController@insertGuest')->name('domisili.insert');
    Route::get('/domisili/print/{id}', 'SuratKeteranganDomisiliController@print')->name('domisili.print');

    Route::get('/pajak', 'SuratKeteranganPajakController@indexGuest')->name('pajak.index');
    Route::post('/pajak', 'SuratKeteranganPajakController@insertGuest')->name('pajak.insert');
    Route::get('/pajak/print/{id}', 'SuratKeteranganPajakController@print')->name('pajak.print');

    Route::get('/kuasa', 'SuratKuasaTanahController@indexGuest')->name('kuasa.index');
    Route::post('/kuasa', 'SuratKuasaTanahController@insertGuest')->name('kuasa.insert');
    Route::get('/kuasa/print/{id}', 'SuratKuasaTanahController@print')->name('kuasa.print');
    
    Route::get('/imb', 'SuratRekomendasiImbController@indexGuest')->name('imb.index');
    Route::post('/imb', 'SuratRekomendasiImbController@insertGuest')->name('imb.insert');
    Route::get('/imb/print/{id}', 'SuratRekomendasiImbController@print')->name('imb.print');

    Route::get('/usaha', 'SuratKeteranganUsahaController@indexGuest')->name('usaha.index');
    Route::post('/usaha', 'SuratKeteranganUsahaController@insertGuest')->name('usaha.insert');
    Route::get('/usaha/print/{id}', 'SuratKeteranganUsahaController@print')->name('usaha.print');

});

Route::group(['prefix' => '/khusus'], function() {
    Route::get('/', 'SuratKhususController@index')->name('khusus.index');

    Route::get('/keramaian', 'SuratKeteranganIzinKeramaianController@indexGuest')->name('keramaian.index');
    Route::post('/keramaian', 'SuratKeteranganIzinKeramaianController@insertGuest')->name('keramaian.insert');
    Route::get('/keramaian/print/{id}', 'SuratKeteranganIzinKeramaianController@print')->name('keramaian.print');

    Route::get('/penghasilan', 'SuratKeteranganPenghasilanController@indexGuest')->name('penghasilan.index');
    Route::post('/penghasilan', 'SuratKeteranganPenghasilanController@insertGuest')->name('penghasilan.insert');
    Route::get('/penghasilan/print/{id}', 'SuratKeteranganPenghasilanController@print')->name('penghasilan.print');

    Route::get('/tidakMampu', 'SuratKeteranganTidakMampuController@indexGuest')->name('tidakMampu.index');
    Route::post('/tidakMampu', 'SuratKeteranganTidakMampuController@insertGuest')->name('tidakMampu.insert');
    Route::get('/tidakMampu/print/{id}', 'SuratKeteranganTidakMampuController@print')->name('tidakMampu.print');

    Route::get('/ahliWaris', 'SuratKeteranganAhliWarisController@indexGuest')->name('ahliWaris.index');
    Route::post('/ahliWaris', 'SuratKeteranganAhliWarisController@insertGuest')->name('ahliWaris.insert');
    Route::get('/ahliWaris/print/{id}', 'SuratKeteranganAhliWarisController@print')->name('ahliWaris.print');

    Route::get('/bedaNama', 'SuratKeteranganBedaNamaController@indexGuest')->name('bedaNama.index');
    Route::post('/bedaNama', 'SuratKeteranganBedaNamaController@insertGuest')->name('bedaNama.insert');
    Route::get('/bedaNama/print/{id}', 'SuratKeteranganBedaNamaController@print')->name('bedaNama.print');

    Route::get('/belumNpwp', 'SuratKeteranganBelumNpwpController@indexGuest')->name('belumNpwp.index');
    Route::post('/belumNpwp', 'SuratKeteranganBelumNpwpController@insertGuest')->name('belumNpwp.insert');
    Route::get('/belumNpwp/print/{id}', 'SuratKeteranganBelumNpwpController@print')->name('belumNpwp.print');

    Route::get('/hibah', 'SuratPernyataanHibahController@indexGuest')->name('hibah.index');
    Route::post('/hibah', 'SuratPernyataanHibahController@insertGuest')->name('hibah.insert');
    Route::get('/hibah/print/{id}', 'SuratPernyataanHibahController@print')->name('hibah.print');

    Route::get('/janda', 'SuratKeteranganJandaController@indexGuest')->name('janda.index');
    Route::post('/janda', 'SuratKeteranganJandaController@insertGuest')->name('janda.insert');
    Route::get('/janda/print/{id}', 'SuratKeteranganJandaController@print')->name('janda.print');

    Route::get('/belumMenikah', 'SuratBelumPernahMenikahController@indexGuest')->name('belumMenikah.index');
    Route::post('/belumMenikah', 'SuratBelumPernahMenikahController@insertGuest')->name('belumMenikah.insert');
    Route::get('/belumMenikah/print/{id}', 'SuratBelumPernahMenikahController@print')->name('belumMenikah.print');

    Route::get('/hubunganKeluarga', 'SuratKeteranganHubunganKeluargaController@indexGuest')->name('hubunganKeluarga.index');
    Route::post('/hubunganKeluarga', 'SuratKeteranganHubunganKeluargaController@insertGuest')->name('hubunganKeluarga.insert');
    Route::get('/hubunganKeluarga/print/{id}', 'SuratKeteranganHubunganKeluargaController@print')->name('hubunganKeluarga.print');

    Route::get('/PanggilanCerai', 'SuratKeteranganPanggilanCeraiController@indexGuest')->name('PanggilanCerai.index');
    Route::post('/PanggilanCerai', 'SuratKeteranganPanggilanCeraiController@insertGuest')->name('PanggilanCerai.insert');
    Route::get('/PanggilanCerai/print/{id}', 'SuratKeteranganPanggilanCeraiController@print')->name('PanggilanCerai.print');

    Route::get('/keterangan', 'SuratKeteranganController@indexGuest')->name('keterangan.index');
    Route::post('/keterangan', 'SuratKeteranganController@insertGuest')->name('keterangan.insert');
    Route::get('/keterangan/print/{id}', 'SuratKeteranganController@print')->name('keterangan.print');

    Route::get('/keteranganKematian', 'SuratKeteranganTentangKematianController@indexGuest')->name('keteranganKematian.index');
    Route::post('/keteranganKematian', 'SuratKeteranganTentangKematianController@insertGuest')->name('keteranganKematian.insert');
    Route::get('/keteranganKematian/print/{id}', 'SuratKeteranganTentangKematianController@print')->name('keteranganKematian.print');

    Route::get('/keteranganKelahiran', 'SuratKeteranganKelahiranController@indexGuest')->name('keteranganKelahiran.index');
    Route::post('/keteranganKelahiran', 'SuratKeteranganKelahiranController@insertGuest')->name('keteranganKelahiran.insert');
    Route::get('/keteranganKelahiran/print/{id}', 'SuratKeteranganKelahiranController@print')->name('keteranganKelahiran.print');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home.index');
Route::get('/about', 'AboutController@index')->name('about.index');
Route::get('/dashboard/{name?}', 'DashboardController@index' )->name('dashboard.index');


Route::resource('preferences', 'PreferenceController')->only(['index', 'store']);
Route::patch('preferences/logo/update', 'PreferenceController@updateLogo')->name('preferences.update.logo');
Route::delete('preferences/logo/destroy', 'PreferenceController@destroyLogo')->name('preferences.destroy.logo');

Route::resource('users', 'UserController');
Route::patch('users/{user}/password/update', 'UserController@updatePassword')->name('users.update.password');

Route::resource('suratKeteranganDomisilis', 'SuratKeteranganDomisiliController');

Route::resource('suratKeteranganIzinKeramaians', 'SuratKeteranganIzinKeramaianController');

Route::resource('suratKeteranganPajaks', 'SuratKeteranganPajakController');

Route::resource('suratKeteranganPenghasilans', 'SuratKeteranganPenghasilanController');

Route::get('documents', 'DocumentController@index')->name('documents.index');


Route::resource('suratRekomendasiImbs', 'SuratRekomendasiImbController');

Route::resource('suratKeteranganUsahas', 'SuratKeteranganUsahaController');

Route::resource('suratKuasaTanahs', 'SuratKuasaTanahController');

Route::resource('suratKeteranganTidakMampus', 'SuratKeteranganTidakMampuController');

Route::resource('suratKeteranganAhliWaris', 'SuratKeteranganAhliWarisController');

Route::resource('ahliWarisKeterenganAhliWaris', 'AhliWarisKeterenganAhliWarisController');

Route::resource('saksiKeteranganAhliWaris', 'SaksiKeteranganAhliWarisController');

Route::resource('suratKeteranganBedaNamas', 'SuratKeteranganBedaNamaController');

Route::resource('suratKeteranganBelumNpwps', 'SuratKeteranganBelumNpwpController');

Route::resource('suratPernyataanHibahs', 'SuratPernyataanHibahController');

Route::resource('riwayatKepemilikanHibahs', 'RiwayatKepemilikanHibahController');

Route::resource('suratKeteranganJandas', 'SuratKeteranganJandaController');

Route::resource('suratBelumPernahMenikahs', 'SuratBelumPernahMenikahController');

Route::resource('suratKeteranganHubunganKeluargas', 'SuratKeteranganHubunganKeluargaController');

Route::resource('suratKeteranganPanggilanCerais', 'SuratKeteranganPanggilanCeraiController');

Route::resource('suratKeterangans', 'SuratKeteranganController');

Route::resource('suratKeteranganTentangKematians', 'SuratKeteranganTentangKematianController');

Route::resource('suratKeteranganKelahirans', 'SuratKeteranganKelahiranController');

app/Models/SuratKeteranganAhliWaris.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class SuratKeteranganAhliWaris
 * @package App\Models
 * @version January 22, 2020, 6:32 am UTC
 *
 * @property \App\Models\Status status
 * @property \App\Models\User user
 * @property \Illuminate\Database\Eloquent\Collection ahliWarisKeteranganAhliWaris
 * @property \Illuminate\Database\Eloquent\Collection saksiKeteranganAhliWaris
 * @property integer user_id
 * @property string nik
 * @property string nama
 * @property string tempat_lahir
 * @property string tanggal_lahir
 * @property string jenis_kelamin
 * @property string kewarganegaraan
 * @property string agama
 * @property string pekerjaan
 * @property string maksud
 * @property integer status_id
 * @property string tanggal_pengajuan
 * @property string tanggal_terbit
 * @property string nomor_surat
 */
class SuratKeteranganAhliWaris extends Model
{
    use SoftDeletes;

    public $table = 'surat_keterangan_ahli_waris';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'user_id',
        'nik',
        'nama',
        'tempat_lahir',
        'tgl_lahir',
        'jenis_kelamin',
        'kewarganegaraan',
        'agama',
        'pekerjaan',
        'maksud',
        'status_id',
        'tanggal_pengajuan',
        'tanggal_terbit',
        'nomor_surat'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'user_id' => 'integer',
        'nik' => 'string',
        'nama' => 'string',
        'tempat_lahir' => 'string',
        'tgl_lahir' => 'date',
        'jenis_kelamin' => 'string',
        'kewarganegaraan' => 'string',
        'agama' => 'string',
        'pekerjaan' => 'string',
        'maksud' => 'string',
        'status_id' => 'integer',
        'tanggal_pengajuan' => 'date',
        'tanggal_terbit' => 'date',
        'nomor_surat' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'nik'                   => 'required|digits:16',
        'nama'                  => 'required',
        'tempat_lahir'          => 'required',
        'tgl_lahir'             => 'required',
        'jenis_kelamin'         => 'required',
        'kewarganegaraan'       => 'required',
        'agama'                 => 'required',
        'pekerjaan'             => 'required',
        'maksud'                => 'required',
        'saksi_pertama'         => 'required',
        'saksi_kedua'           => 'required',
        "ahli_waris"            => "required|array|min:1",
        "ahli_waris.*"          => "required|string|distinct",
        "hubungan_ahli_waris"   => "required|array|min:1",
        "hubungan_ahli_waris.*" => "required|string|distinct",
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function status()
    {
        return $this->belongsTo(\App\Models\Status::class, 'status_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function user()
    {
        return $this->belongsTo(\App\Models\User::class, 'user_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function ahliWarisKeteranganAhliWaris()
    {
        return $this->hasMany(\App\Models\AhliWarisKeterenganAhliWaris::class, 'ahli_waris_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function saksiKeteranganAhliWaris()
    {
        return $this->hasMany(\App\Models\SaksiKeteranganAhliWaris::class, 'ahli_waris_id');
    }

    public function getTglLahirAttribute( $date )
    {
        return date( 'Y-m-d', strtotime( $date ) );
    }
}

resources/views/surat_keterangan_ahli_waris/fields.blade.php
@section('scripts')
<script type="text/javascript">
    $('#tgl_lahir').datetimepicker({
        format: 'YYYY-MM-DD',
        useCurrent: false
    });

    $(document).ready(function() {
        var max_fields = 20; //maximum input boxes allowed
        var wrapper = $("#items"); //Fields wrapper
        var add_button = $(".add_field_button"); //Add button ID
        
        var x = 1; //initlal text box count
        $(add_button).click(function(e){ //on add input button click
            e.preventDefault();
            if(x < max_fields){ //max input box allowed
                x++; //text box increment
                console.log(x);
                $(wrapper).append(
                    "<div class='form-group col-sm-12'>"+
                        "<div class='form-group col-sm-6'>"+
                            "<label>Ahli Waris :</label>"+
                            "<input id='ahli_waris' class='form-control' name='ahli_waris[]' required='required' type='text' />"+
                        "</div>"+
                        "<div class='form-group col-sm-6'>"+
                            "<label>Hubungan Waris:</label>"+
                            "<input id='hubungan_ahli_waris' class='form-control' name='hubungan_ahli_waris[]' required='required' type='text' />"+
                        "</div>"+
                        "<a href='#' class='remove_field'>"+
                            "<i class='fa fa-times'></i>"+
                        "</a>"+
                    "</div>"
                ); //add input box
            }
        });
     
        $(wrapper).on("click",".remove_field", function(e){ //user click on remove field
            e.preventDefault(); $(this).parent('div').remove(); x--;
        })
    });

    @if(session('status'))
        document.getElementById("print").click();
    @endif
</script>
@endsection

<div class="col-sm-6">
    <!-- Nik Field -->
    <div class="form-group col-sm-12">
        {!! Form::label('nik', 'NIK:') !!}
        {!! Form::text('nik', null, ['class' => 'form-control', 'maxlength' => '16']) !!}
    </div>

    <!-- Nama Field -->
    <div class="form-group col-sm-12">
        {!! Form::label('nama', 'Nama:') !!}
        {!! Form::text('nama', null, ['class' => 'form-control']) !!}
    </div>

    <!-- Tempat Lahir Field -->
    <div class="form-group col-sm-12">
        {!! Form::label('tempat_lahir', 'Tempat Lahir:') !!}
        {!! Form::text('tempat_lahir', null, ['class' => 'form-control']) !!}
    </div>

    <!-- Tanggal Lahir Field -->
    <div class="form-group col-sm-12">
        {!! Form::label('Tanggal Lahir', 'Tanggal Lahir:') !!}
        {!! Form::date('tgl_lahir', null, ['class' => 'form-control','id'=>'tgl_lahir']) !!}
    </div>

    <!-- Jenis Kelamin Field -->
    <div class="form-group col-sm-12">
        <label for="jenis_kelamin">
            Jenis Kelamin
        </label>
        @isset($suratKeteranganAhliWaris)
            <div class="form-check">
                <label class="form-check-label">
                    <input type="radio" class="form-check-input" name="jenis_kelamin" id="jenis_kelamin" value="Laki-Laki" 
                    {{ (old('jenis_kelamin') == 'Laki-Laki' || $suratKeteranganAhliWaris->jenis_kelamin == 'Laki-Laki') ? "checked" : "" }}
                    >Laki-Laki
                </label>
            </div>
            <div class="form-check">
                <label class="form-check-label">
                    <input type="radio" class="form-check-input" name="jenis_kelamin" id="jenis_kelamin" value="Perempuan"
                    {{ (old('jenis_kelamin') == 'Perempuan' || $suratKeteranganAhliWaris->jenis_kelamin == 'Perempuan') ? "checked" : "" }}
                    >Perempuan
                </label>
            </div>
        @endisset

        @empty($suratKeteranganAhliWaris)
        <div class="form-check">
                <label class="form-check-label">
                    <input type="radio" class="form-check-input" name="jenis_kelamin" id="jenis_kelamin" value="Laki-Laki" 
                    {{ (old('jenis_kelamin') == 'Laki-Laki') ? "checked" : "" }}
                    >Laki-Laki
                </label>
            </div>
            <div class="form-check">
                <label class="form-check-label">
                    <input type="radio" class="form-check-input" name="jenis_kelamin" id="jenis_kelamin" value="Perempuan"
                    {{ (old('jenis_kelamin') == 'Perempuan') ? "checked" : "" }}
                    >Perempuan
                </label>
            </div>
        @endempty
    </div>

    <!-- Kewarganegaraan Field -->
    <div class="form-group col-sm-12">
        {!! Form::label('kewarganegaraan', 'Kewarganegaraan:') !!}
        {!! Form::text('kewarganegaraan', null, ['class' => 'form-control']) !!}
    </div>

    <!-- Agama Field -->
    <div class="form-group col-sm-12">
        <label for="agama">Agama</label>
        <select class="form-control" id="agama" name="agama" >
            @isset($suratKeteranganAhliWaris)
                <option value="Islam" {{ (old('agama') == 'Islam') || $suratKeteranganAhliWaris->agama == 'Islam' ? "selected" : "" }}>Islam</option>
                <option value="Protestan" {{ (old('agama') == 'Protestan') || $suratKeteranganAhliWaris->agama == 'Protestan' ? "selected" : "" }}>Protestan</option>
                <option value="Katolik" {{ (old('agama') == 'Katolik') || $suratKeteranganAhliWaris->agama == 'Katolik' ? "selected" : "" }}>Katolik</option>
                <option value="Hindu" {{ (old('agama') == 'Hindu') || $suratKeteranganAhliWaris->agama == 'Hindu' ? "selected" : "" }}>Hindu</option>
                <option value="Buddha" {{ (old('agama') == 'Buddha') || $suratKeteranganAhliWaris->agama == 'Buddha' ? "selected" : "" }}>Buddha</option>
                <option value="Khonghucu" {{ (old('agama') == 'Khonghucu') || $suratKeteranganAhliWaris->agama == 'Konghucu' ? "selected" : "" }}>Khonghucu</option>
            @endisset
    
            @empty($suratKeteranganAhliWaris)
                <option value="Islam" {{ (old('agama') == 'Islam') ? "selected" : "" }}>Islam</option>
                <option value="Protestan" {{ (old('agama') == 'Protestan') ? "selected" : "" }}>Protestan</option>
                <option value="Katolik" {{ (old('agama') == 'Katolik') ? "selected" : "" }}>Katolik</option>
                <option value="Hindu" {{ (old('agama') == 'Hindu') ? "selected" : "" }}>Hindu</option>
                <option value="Buddha" {{ (old('agama') == 'Buddha') ? "selected" : "" }}>Buddha</option>
                <option value="Khonghucu" {{ (old('agama') == 'Khonghucu') ? "selected" : "" }}>Khonghucu</option>
            @endempty
        </select>
    </div>

    <!-- Pekerjaan Field -->
    <div class="form-group col-sm-12">
        {!! Form::label('pekerjaan', 'Pekerjaan:') !!}
        {!! Form::text('pekerjaan', null, ['class' => 'form-control']) !!}
    </div>

    <!-- Maksud Field -->
    <div class="form-group col-sm-12">
        {!! Form::label('maksud', 'Maksud:') !!}
        {!! Form::text('maksud', null, ['class' => 'form-control']) !!}
    </div>
    
    <div class="form-group col-sm-12">
        <div id="items">
        @isset($suratKeteranganAhliWaris->ahliWarisKeteranganAhliWaris)
            @if ($x = 1) @endif
            @foreach ($suratKeteranganAhliWaris->ahliWarisKeteranganAhliWaris as $item)
                <div class="form-group col-sm-12">
                    <div class="form-group col-sm-6">
                        <label>Ahli Waris:</label>
                        <input id="ahli_waris" class="form-control" name="ahli_waris[{{$item->id}}]" required="required" type="text" value="{{ $item->nama }}" />
                    </div>
                    <div class="form-group col-sm-6">
                        <label>Hubungan Waris:</label>
                        <input id="hubungan_ahli_waris" class="form-control" name="hubungan_ahli_waris[{{$item->id}}]" required="required" type="text" value="{{ $item->hubungan }}" />
                    </div>
                    <a href='#' class='remove_field'>
                        <i class='fa fa-times'></i>
                    </a>
                </div>
                @if ($x++) @endif
            @endforeach
        @endisset

        @empty($suratKeteranganAhliWaris->ahliWarisKeteranganAhliWaris)
        <div class="row">
            <div class="row">
                <div class="form-group col-sm-12">
                    <div class="form-group col-sm-6">
                        <label>Ahli Waris 1:</label>
                        <input id="ahli_waris" class="form-control" name="ahli_waris[]" required="required" type="text" />
                    </div>
                    <div class="form-group col-sm-6">
                        <label>Hubungan Waris 1:</label>
                        <input id="hubungan_ahli_waris" class="form-control" name="hubungan_ahli_waris[]" required="required" type="text" />
                    </div>
                </div>
            </div>
        </div>
        @endempty
        </div>
        <button type="button" class="add_field_button">Tambahkan Ahli Waris</button>
    </div>

    <div class="form-group col-sm-12">
        <label>
            Saksi Pertama
        </label>

        @isset($suratKeteranganAhliWaris->saksiKeteranganAhliWaris[0])
            <input type="hidden" class="form-control" id="saksi_pertama_id" name="saksi_pertama_id" 
                value="{{ $suratKeteranganAhliWaris->saksiKeteranganAhliWaris[0]->id }}"
            required>
        @endisset

        <input type="text" class="form-control" id="saksi_pertama" name="saksi_pertama" 
            @isset($suratKeteranganAhliWaris->saksiKeteranganAhliWaris[0])
                value="{{ $suratKeteranganAhliWaris->saksiKeteranganAhliWaris[0]->nama }}"
            @endisset    
        required>
    </div>

    <div class="form-group col-sm-12">
        <label>
            Saksi Kedua
        </label>
        @isset($suratKeteranganAhliWaris->saksiKeteranganAhliWaris[1])
            <input type="hidden" class="form-control" id="saksi_pertama_id" name="saksi_kedua_id" 
                value="{{ $suratKeteranganAhliWaris->saksiKeteranganAhliWaris[1]->id }}"
            required>
        @endisset 

        <input type="text" class="form-control" id="saksi_kedua" name="saksi_kedua" 
            @isset($suratKeteranganAhliWaris->saksiKeteranganAhliWaris[1])
                value="{{ $suratKeteranganAhliWaris->saksiKeteranganAhliWaris[1]->nama }}"
            @endisset 
        required>
    </div>

    @if(Route::current()->getName() == 'suratKeteranganAhliWaris.edit')
        <!-- Status Id Field -->
        <div class="form-group col-sm-12">
            {!! Form::label('status_id', 'Status Id') !!}
            <input class="form-control" name="status" id="status" type="text" value="{{$suratKeteranganAhliWaris->status->status}}" readonly>
        </div>
    @endif
</div>

<div class="col-sm-12">
@if(Route::current()->getName() == 'suratKeteranganAhliWaris.edit')
    @if ( $suratKeteranganAhliWaris->status->status == "Draf" )
        <!-- Submit Field -->
        <div class="form-group col-sm-12">
            {!! Form::submit('Terima', ['class' => 'btn btn-primary', 'name' => 'terima', 'onClick' => 'redirect()']) !!}
            {!! Form::submit('Tolak', ['class' => 'btn btn-danger', 'name' => 'tolak']) !!}
            <a href="{!! route('suratKeteranganAhliWaris.index') !!}" class="btn btn-default">Kembali</a>
        </div>
    @elseif ( $suratKeteranganAhliWaris->status->status == "Diterima" )
        <!-- Submit Field -->
        <div class="form-group col-sm-12">
            <a href="{{ route('ahliWaris.print', ['id' => $suratKeteranganAhliWaris->id]) }}" class="btn btn-success" target="_blank" id="print">
                Print
            </a>
            <a href="{!! route('suratKeteranganAhliWaris.index') !!}" class="btn btn-default">Kembali</a>
        </div>
    @else
        <!-- Submit Field -->
        <div class="form-group col-sm-12">
            <a href="{!! route('suratKeteranganAhliWaris.index') !!}" class="btn btn-default">Kembali</a>
        </div>
    @endif
@else
    <!-- Submit Field -->
    <div class="form-group col-sm-12">
        {!! Form::submit('Buat Surat Keterangan Ahli Waris', ['class' => 'btn btn-primary']) !!}
        <a href="{!! route('suratKeteranganAhliWaris.index') !!}" class="btn btn-default">kembali</a>
    </div>
@endif
</div>

resources/views/surat_keterangan_ahli_waris/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Surat Keterangan Ahli Waris</h1>
    </section>
    <div class="clearfix"></div>
    <br>
    <div class="col-sm-4">
        <a class="btn btn-primary" href="{{ route('suratKeteranganAhliWaris.create') }}">Pengajuan Surat Keterangan Ahli Waris</a>
    </div>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                <div class="col-sm-12">
                    @include('surat_keterangan_ahli_waris.table')
                </div>
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/surat_keterangan_ahli_waris/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Surat Keterangan Ahli Waris
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('surat_keterangan_ahli_waris.show_fields')
                    <a href="{{ route('suratKeteranganAhliWaris.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection