routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if ( !auth()->user() )
        return view('general.index');
    else
        return redirect()->to( 'home' );
});


Route::group(['prefix' => '/umum'], function() {
    Route::get('/', 'SuratUmumController@index')->name('umum.index');

    Route::get('/domisili', 'SuratKeteranganDomisiliController@indexGuest')->name('domisili.index');
    Route::post('/domisili', 'SuratKeteranganDomisiliController@insertGuest')->name('domisili.insert');
    Route::get('/domisili/print/{id}', 'SuratKeteranganDomisiliController@print')->name('domisili.print');

    Route::get('/pajak', 'SuratKeteranganPajakController@indexGuest')->name('pajak.index');
    Route::post('/pajak', 'SuratKeteranganPajakController@insertGuest')->name('pajak.insert');
    Route::get('/pajak/print/{id}', 'SuratKeteranganPajakController@print')->name('pajak.print');

    Route::get('/kuasa', 'SuratKuasaTanahController@indexGuest')->name('kuasa.index');
    Route::post('/kuasa', 'SuratKuasaTanahController@insertGuest')->name('kuasa.insert');
    Route::get('/kuasa/print/{id}', 'SuratKuasaTanahController@print')->name('kuasa.print');
    
    Route::get('/imb', 'SuratRekomendasiImbController@indexGuest')->name('imb.index');
    Route::post('/imb', 'SuratRekomendasiImbController@insertGuest')->name('imb.insert');
    Route::get('/imb/print/{id}', 'SuratRekomendasiImbController@print')->name('imb.print');

    Route::get('/usaha', 'SuratKeteranganUsahaController@indexGuest')->name('usaha.index');
    Route::post('/usaha', 'SuratKeteranganUsahaController@insertGuest')->name('usaha.insert');
    Route::get('/usaha/print/{id}', 'SuratKeteranganUsahaController@print')->name('usaha.print');

});

Route::group(['prefix' => '/khusus'], function() {
    Route::get('/', 'SuratKhususController@index')->name('khusus.index');

    Route::get('/keramaian', 'SuratKeteranganIzinKeramaianController@indexGuest')->name('keramaian.index');
    Route::post('/keramaian', 'SuratKeteranganIzinKeramaianController@insertGuest')->name('keramaian.insert');
    Route::get('/keramaian/print/{id}', 'SuratKeteranganIzinKeramaianController@print')->name('keramaian.print');

    Route::get('/penghasilan', 'SuratKeteranganPenghasilanController@indexGuest')->name('penghasilan.index');
    Route::post('/penghasilan', 'SuratKeteranganPenghasilanController@insertGuest')->name('penghasilan.insert');
    Route::get('/penghasilan/print/{id}', 'SuratKeteranganPenghasilanController@print')->name('penghasilan.print');

    Route::get('/tidakMampu', 'SuratKeteranganTidakMampuController@indexGuest')->name('tidakMampu.index');
    Route::post('/tidakMampu', 'SuratKeteranganTidakMampuController@insertGuest')->name('tidakMampu.insert');
    Route::get('/tidakMampu/print/{id}', 'SuratKeteranganTidakMampuController@print')->name('tidakMampu.print');

    Route::get('/ahliWaris', 'SuratKeteranganAhliWarisController@indexGuest')->name('ahliWaris.index');
    Route::post('/ahliWaris', 'SuratKeteranganAhliWarisController@insertGuest')->name('ahliWaris.insert');
    Route::get('/ahliWaris/print/{id}', 'SuratKeteranganAhliWarisController@print')->name('ahliWaris.print');

    Route::get('/bedaNama', 'SuratKeteranganBedaNamaController@indexGuest')->name('bedaNama.index');
    Route::post('/bedaNama', 'SuratKeteranganBedaNamaController@insertGuest')->name('bedaNama.insert');
    Route::get('/bedaNama/print/{id}', 'SuratKeteranganBedaNamaController@print')->name('bedaNama.print');

    Route::get('/belumNpwp', 'SuratKeteranganBelumNpwpController@indexGuest')->name('belumNpwp.index');
    Route::post('/belumNpwp', 'SuratKeteranganBelumNpwpController@insertGuest')->name('belumNpwp.insert');
    Route::get('/belumNpwp/print/{id}', 'SuratKeteranganBelumNpwpController@print')->name('belumNpwp.print');

    Route::get('/hibah', 'SuratPernyataanHibahController@indexGuest')->name('hibah.index');
    Route::post('/hibah', 'SuratPernyataanHibahController@insertGuest')->name('hibah.insert');
    Route::get('/hibah/print/{id}', 'SuratPernyataanHibahController@print')->name('hibah.print');

    Route::get('/janda', 'SuratKeteranganJandaController@indexGuest')->name('janda.index');
    Route::post('/janda', 'SuratKeteranganJandaController@insertGuest')->name('janda.insert');
    Route::get('/janda/print/{id}', 'SuratKeteranganJandaController@print')->name('janda.print');

    Route::get('/belumMenikah', 'SuratBelumPernahMenikahController@indexGuest')->name('belumMenikah.index');
    Route::post('/belumMenikah', 'SuratBelumPernahMenikahController@insertGuest')->name('belumMenikah.insert');
    Route::get('/belumMenikah/print/{id}', 'SuratBelumPernahMenikahController@print')->name('belumMenikah.print');

    Route::get('/hubunganKeluarga', 'SuratKeteranganHubunganKeluargaController@indexGuest')->name('hubunganKeluarga.index');
    Route::post('/hubunganKeluarga', 'SuratKeteranganHubunganKeluargaController@insertGuest')->name('hubunganKeluarga.insert');
    Route::get('/hubunganKeluarga/print/{id}', 'SuratKeteranganHubunganKeluargaController@print')->name('hubunganKeluarga.print');

    Route::get('/PanggilanCerai', 'SuratKeteranganPanggilanCeraiController@indexGuest')->name('PanggilanCerai.index');
    Route::post('/PanggilanCerai', 'SuratKeteranganPanggilanCeraiController@insertGuest')->name('PanggilanCerai.insert');
    Route::get('/PanggilanCerai/print/{id}', 'SuratKeteranganPanggilanCeraiController@print')->name('PanggilanCerai.print');

    Route::get('/keterangan', 'SuratKeteranganController@indexGuest')->name('keterangan.index');
    Route::post('/keterangan', 'SuratKeteranganController@insertGuest')->name('keterangan.insert');
    Route::get('/keterangan/print/{id}', 'SuratKeteranganController@print')->name('keterangan.print');

    Route::get('/keteranganKematian', 'SuratKeteranganTentangKematianController@indexGuest')->name('keteranganKematian.index');
    Route::post('/keteranganKematian', 'SuratKeteranganTentangKematianController@insertGuest')->name('keteranganKematian.insert');
    Route::get('/keteranganKematian/print/{id}', 'SuratKeteranganTentangKematianController@print')->name('keteranganKematian.print');

    Route::get('/keteranganKelahiran', 'SuratKeteranganKelahiranController@indexGuest')->name('keteranganKelahiran.index');
    Route::post('/keteranganKelahiran', 'SuratKeteranganKelahiranController@insertGuest')->name('keteranganKelahiran.insert');
    Route::get('/keteranganKelahiran/print/{id}', 'SuratKeteranganKelahiranController@print')->name('keteranganKelahiran.print');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home.index');
Route::get('/about', 'AboutController@index')->name('about.index');
Route::get('/dashboard/{name?}', 'DashboardController@index' )->name('dashboard.index');


Route::resource('preferences', 'PreferenceController')->only(['index', 'store']);
Route::patch('preferences/logo/update', 'PreferenceController@updateLogo')->name('preferences.update.logo');
Route::delete('preferences/logo/destroy', 'PreferenceController@destroyLogo')->name('preferences.destroy.logo');

Route::resource('users', 'UserController');
Route::patch('users/{user}/password/update', 'UserController@updatePassword')->name('users.update.password');

Route::resource('suratKeteranganDomisilis', 'SuratKeteranganDomisiliController');

Route::resource('suratKeteranganIzinKeramaians', 'SuratKeteranganIzinKeramaianController');

Route::resource('suratKeteranganPajaks', 'SuratKeteranganPajakController');

Route::resource('suratKeteranganPenghasilans', 'SuratKeteranganPenghasilanController');

Route::get('documents', 'DocumentController@index')->name('documents.index');


Route::resource('suratRekomendasiImbs', 'SuratRekomendasiImbController');

Route::resource('suratKeteranganUsahas', 'SuratKeteranganUsahaController');

Route::resource('suratKuasaTanahs', 'SuratKuasaTanahController');

Route::resource('suratKeteranganTidakMampus', 'SuratKeteranganTidakMampuController');

Route::resource('suratKeteranganAhliWaris', 'SuratKeteranganAhliWarisController');

Route::resource('ahliWarisKeterenganAhliWaris', 'AhliWarisKeterenganAhliWarisController');

Route::resource('saksiKeteranganAhliWaris', 'SaksiKeteranganAhliWarisController');

Route::resource('suratKeteranganBedaNamas', 'SuratKeteranganBedaNamaController');

Route::resource('suratKeteranganBelumNpwps', 'SuratKeteranganBelumNpwpController');

Route::resource('suratPernyataanHibahs', 'SuratPernyataanHibahController');

Route::resource('riwayatKepemilikanHibahs', 'RiwayatKepemilikanHibahController');

Route::resource('suratKeteranganJandas', 'SuratKeteranganJandaController');

Route::resource('suratBelumPernahMenikahs', 'SuratBelumPernahMenikahController');

Route::resource('suratKeteranganHubunganKeluargas', 'SuratKeteranganHubunganKeluargaController');

Route::resource('suratKeteranganPanggilanCerais', 'SuratKeteranganPanggilanCeraiController');

Route::resource('suratKeterangans', 'SuratKeteranganController');

Route::resource('suratKeteranganTentangKematians', 'SuratKeteranganTentangKematianController');

Route::resource('suratKeteranganKelahirans', 'SuratKeteranganKelahiranController');

app/Models/AhliWarisKeterenganAhliWaris.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class AhliWarisKeterenganAhliWaris
 * @package App\Models
 * @version January 29, 2020, 5:58 am UTC
 *
 * @property \App\Models\SuratKeteranganAhliWari ahliWaris
 * @property integer ahli_waris_id
 * @property string nama
 * @property string hubungan
 */
class AhliWarisKeterenganAhliWaris extends Model
{
    use SoftDeletes;

    public $table = 'ahli_waris_keterangan_ahli_waris';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'ahli_waris_id',
        'nama',
        'hubungan'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'ahli_waris_id' => 'integer',
        'nama' => 'string',
        'hubungan' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'ahli_waris_id' => 'required',
        'nama' => 'required',
        'hubungan' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function ahliWaris()
    {
        return $this->belongsTo(\App\Models\SuratKeteranganAhliWari::class, 'ahli_waris_id');
    }
}

app/Http/Controllers/AhliWarisKeterenganAhliWarisController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateAhliWarisKeterenganAhliWarisRequest;
use App\Http\Requests\UpdateAhliWarisKeterenganAhliWarisRequest;
use App\Repositories\AhliWarisKeterenganAhliWarisRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class AhliWarisKeterenganAhliWarisController extends AppBaseController
{
    /** @var  AhliWarisKeterenganAhliWarisRepository */
    private $ahliWarisKeterenganAhliWarisRepository;

    public function __construct(AhliWarisKeterenganAhliWarisRepository $ahliWarisKeterenganAhliWarisRepo)
    {
        $this->ahliWarisKeterenganAhliWarisRepository = $ahliWarisKeterenganAhliWarisRepo;
    }

    /**
     * Display a listing of the AhliWarisKeterenganAhliWaris.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $ahliWarisKeterenganAhliWaris = $this->ahliWarisKeterenganAhliWarisRepository->all();
        //test
        return view('ahli_waris_keterengan_ahli_waris.index')
            ->with('ahliWarisKeterenganAhliWaris', $ahliWarisKeterenganAhliWaris);
    }

    /**
     * Show the form for creating a new AhliWarisKeterenganAhliWaris.
     *
     * @return Response
     */
    public function create()
    {
        return view('ahli_waris_keterengan_ahli_waris.create');
    }

    /**
     * Store a newly created AhliWarisKeterenganAhliWaris in storage.
     *
     * @param CreateAhliWarisKeterenganAhliWarisRequest $request
     *
     * @return Response
     */
    public function store(CreateAhliWarisKeterenganAhliWarisRequest $request)
    {
        $input = $request->all();

        $ahliWarisKeterenganAhliWaris = $this->ahliWarisKeterenganAhliWarisRepository->create($input);

        Flash::success('Ahli Waris Keterengan Ahli Waris saved successfully.');

        return redirect(route('ahliWarisKeterenganAhliWaris.index'));
    }

    /**
     * Display the specified AhliWarisKeterenganAhliWaris.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $ahliWarisKeterenganAhliWaris = $this->ahliWarisKeterenganAhliWarisRepository->find($id);

        if (empty($ahliWarisKeterenganAhliWaris)) {
            Flash::error('Ahli Waris Keterengan Ahli Waris not found');

            return redirect(route('ahliWarisKeterenganAhliWaris.index'));
        }

        return view('ahli_waris_keterengan_ahli_waris.show')->with('ahliWarisKeterenganAhliWaris', $ahliWarisKeterenganAhliWaris);
    }

    /**
     * Show the form for editing the specified AhliWarisKeterenganAhliWaris.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $ahliWarisKeterenganAhliWaris = $this->ahliWarisKeterenganAhliWarisRepository->find($id);

        if (empty($ahliWarisKeterenganAhliWaris)) {
            Flash::error('Ahli Waris Keterengan Ahli Waris not found');

            return redirect(route('ahliWarisKeterenganAhliWaris.index'));
        }

        return view('ahli_waris_keterengan_ahli_waris.edit')->with('ahliWarisKeterenganAhliWaris', $ahliWarisKeterenganAhliWaris);
    }

    /**
     * Update the specified AhliWarisKeterenganAhliWaris in storage.
     *
     * @param int $id
     * @param UpdateAhliWarisKeterenganAhliWarisRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateAhliWarisKeterenganAhliWarisRequest $request)
    {
        $ahliWarisKeterenganAhliWaris = $this->ahliWarisKeterenganAhliWarisRepository->find($id);

        if (empty($ahliWarisKeterenganAhliWaris)) {
            Flash::error('Ahli Waris Keterengan Ahli Waris not found');

            return redirect(route('ahliWarisKeterenganAhliWaris.index'));
        }

        $ahliWarisKeterenganAhliWaris = $this->ahliWarisKeterenganAhliWarisRepository->update($request->all(), $id);

        Flash::success('Ahli Waris Keterengan Ahli Waris updated successfully.');

        return redirect(route('ahliWarisKeterenganAhliWaris.index'));
    }

    /**
     * Remove the specified AhliWarisKeterenganAhliWaris from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $ahliWarisKeterenganAhliWaris = $this->ahliWarisKeterenganAhliWarisRepository->find($id);

        if (empty($ahliWarisKeterenganAhliWaris)) {
            Flash::error('Ahli Waris Keterengan Ahli Waris not found');

            return redirect(route('ahliWarisKeterenganAhliWaris.index'));
        }

        $this->ahliWarisKeterenganAhliWarisRepository->delete($id);

        Flash::success('Ahli Waris Keterengan Ahli Waris deleted successfully.');

        return redirect(route('ahliWarisKeterenganAhliWaris.index'));
    }
}

resources/views/ahli_waris_keterengan_ahli_waris/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Ahli Waris Keterengan Ahli Waris
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'ahliWarisKeterenganAhliWaris.store']) !!}

                        @include('ahli_waris_keterengan_ahli_waris.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/ahli_waris_keterengan_ahli_waris/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Ahli Waris Keterengan Ahli Waris
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($ahliWarisKeterenganAhliWaris, ['route' => ['ahliWarisKeterenganAhliWaris.update', $ahliWarisKeterenganAhliWaris->id], 'method' => 'patch']) !!}

                        @include('ahli_waris_keterengan_ahli_waris.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/ahli_waris_keterengan_ahli_waris/fields.blade.php
<!-- Ahli Waris Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ahli_waris_id', 'Ahli Waris Id:') !!}
    {!! Form::number('ahli_waris_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Nama Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nama', 'Nama:') !!}
    {!! Form::text('nama', null, ['class' => 'form-control']) !!}
</div>

<!-- Hubungan Field -->
<div class="form-group col-sm-6">
    {!! Form::label('hubungan', 'Hubungan:') !!}
    {!! Form::text('hubungan', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('ahliWarisKeterenganAhliWaris.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/ahli_waris_keterengan_ahli_waris/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Ahli Waris Keterengan Ahli Waris</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('ahliWarisKeterenganAhliWaris.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('ahli_waris_keterengan_ahli_waris.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/ahli_waris_keterengan_ahli_waris/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Ahli Waris Keterengan Ahli Waris
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('ahli_waris_keterengan_ahli_waris.show_fields')
                    <a href="{{ route('ahliWarisKeterenganAhliWaris.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/ahli_waris_keterengan_ahli_waris/show_fields.blade.php
<!-- Ahli Waris Id Field -->
<div class="form-group">
    {!! Form::label('ahli_waris_id', 'Ahli Waris Id:') !!}
    <p>{{ $ahliWarisKeterenganAhliWaris->ahli_waris_id }}</p>
</div>

<!-- Nama Field -->
<div class="form-group">
    {!! Form::label('nama', 'Nama:') !!}
    <p>{{ $ahliWarisKeterenganAhliWaris->nama }}</p>
</div>

<!-- Hubungan Field -->
<div class="form-group">
    {!! Form::label('hubungan', 'Hubungan:') !!}
    <p>{{ $ahliWarisKeterenganAhliWaris->hubungan }}</p>
</div>

resources/views/ahli_waris_keterengan_ahli_waris/table.blade.php
<div class="table-responsive">
    <table class="table" id="ahliWarisKeterenganAhliWaris-table">
        <thead>
            <tr>
                <th>Ahli Waris Id</th>
        <th>Nama</th>
        <th>Hubungan</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($ahliWarisKeterenganAhliWaris as $ahliWarisKeterenganAhliWaris)
            <tr>
                <td>{{ $ahliWarisKeterenganAhliWaris->ahli_waris_id }}</td>
            <td>{{ $ahliWarisKeterenganAhliWaris->nama }}</td>
            <td>{{ $ahliWarisKeterenganAhliWaris->hubungan }}</td>
                <td>
                    {!! Form::open(['route' => ['ahliWarisKeterenganAhliWaris.destroy', $ahliWarisKeterenganAhliWaris->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('ahliWarisKeterenganAhliWaris.show', [$ahliWarisKeterenganAhliWaris->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{{ route('ahliWarisKeterenganAhliWaris.edit', [$ahliWarisKeterenganAhliWaris->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>