routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if ( !auth()->user() )
        return view('general.index');
    else
        return redirect()->to( 'home' );
});


Route::group(['prefix' => '/umum'], function() {
    Route::get('/', 'SuratUmumController@index')->name('umum.index');

    Route::get('/domisili', 'SuratKeteranganDomisiliController@indexGuest')->name('domisili.index');
    Route::post('/domisili', 'SuratKeteranganDomisiliController@insertGuest')->name('domisili.insert');
    Route::get('/domisili/print/{id}', 'SuratKeteranganDomisiliController@print')->name('domisili.print');

    Route::get('/pajak', 'SuratKeteranganPajakController@indexGuest')->name('pajak.index');
    Route::post('/pajak', 'SuratKeteranganPajakController@insertGuest')->name('pajak.insert');
    Route::get('/pajak/print/{id}', 'SuratKeteranganPajakController@print')->name('pajak.print');

    Route::get('/kuasa', 'SuratKuasaTanahController@indexGuest')->name('kuasa.index');
    Route::post('/kuasa', 'SuratKuasaTanahController@insertGuest')->name('kuasa.insert');
    Route::get('/kuasa/print/{id}', 'SuratKuasaTanahController@print')->name('kuasa.print');
    
    Route::get('/imb', 'SuratRekomendasiImbController@indexGuest')->name('imb.index');
    Route::post('/imb', 'SuratRekomendasiImbController@insertGuest')->name('imb.insert');
    Route::get('/imb/print/{id}', 'SuratRekomendasiImbController@print')->name('imb.print');

    Route::get('/usaha', 'SuratKeteranganUsahaController@indexGuest')->name('usaha.index');
    Route::post('/usaha', 'SuratKeteranganUsahaController@insertGuest')->name('usaha.insert');
    Route::get('/usaha/print/{id}', 'SuratKeteranganUsahaController@print')->name('usaha.print');

});

Route::group(['prefix' => '/khusus'], function() {
    Route::get('/', 'SuratKhususController@index')->name('khusus.index');

    Route::get('/keramaian', 'SuratKeteranganIzinKeramaianController@indexGuest')->name('keramaian.index');
    Route::post('/keramaian', 'SuratKeteranganIzinKeramaianController@insertGuest')->name('keramaian.insert');
    Route::get('/keramaian/print/{id}', 'SuratKeteranganIzinKeramaianController@print')->name('keramaian.print');

    Route::get('/penghasilan', 'SuratKeteranganPenghasilanController@indexGuest')->name('penghasilan.index');
    Route::post('/penghasilan', 'SuratKeteranganPenghasilanController@insertGuest')->name('penghasilan.insert');
    Route::get('/penghasilan/print/{id}', 'SuratKeteranganPenghasilanController@print')->name('penghasilan.print');

    Route::get('/tidakMampu', 'SuratKeteranganTidakMampuController@indexGuest')->name('tidakMampu.index');
    Route::post('/tidakMampu', 'SuratKeteranganTidakMampuController@insertGuest')->name('tidakMampu.insert');
    Route::get('/tidakMampu/print/{id}', 'SuratKeteranganTidakMampuController@print')->name('tidakMampu.print');

    Route::get('/ahliWaris', 'SuratKeteranganAhliWarisController@indexGuest')->name('ahliWaris.index');
    Route::post('/ahliWaris', 'SuratKeteranganAhliWarisController@insertGuest')->name('ahliWaris.insert');
    Route::get('/ahliWaris/print/{id}', 'SuratKeteranganAhliWarisController@print')->name('ahliWaris.print');

    Route::get('/bedaNama', 'SuratKeteranganBedaNamaController@indexGuest')->name('bedaNama.index');
    Route::post('/bedaNama', 'SuratKeteranganBedaNamaController@insertGuest')->name('bedaNama.insert');
    Route::get('/bedaNama/print/{id}', 'SuratKeteranganBedaNamaController@print')->name('bedaNama.print');

    Route::get('/belumNpwp', 'SuratKeteranganBelumNpwpController@indexGuest')->name('belumNpwp.index');
    Route::post('/belumNpwp', 'SuratKeteranganBelumNpwpController@insertGuest')->name('belumNpwp.insert');
    Route::get('/belumNpwp/print/{id}', 'SuratKeteranganBelumNpwpController@print')->name('belumNpwp.print');

    Route::get('/hibah', 'SuratPernyataanHibahController@indexGuest')->name('hibah.index');
    Route::post('/hibah', 'SuratPernyataanHibahController@insertGuest')->name('hibah.insert');
    Route::get('/hibah/print/{id}', 'SuratPernyataanHibahController@print')->name('hibah.print');

    Route::get('/janda', 'SuratKeteranganJandaController@indexGuest')->name('janda.index');
    Route::post('/janda', 'SuratKeteranganJandaController@insertGuest')->name('janda.insert');
    Route::get('/janda/print/{id}', 'SuratKeteranganJandaController@print')->name('janda.print');

    Route::get('/belumMenikah', 'SuratBelumPernahMenikahController@indexGuest')->name('belumMenikah.index');
    Route::post('/belumMenikah', 'SuratBelumPernahMenikahController@insertGuest')->name('belumMenikah.insert');
    Route::get('/belumMenikah/print/{id}', 'SuratBelumPernahMenikahController@print')->name('belumMenikah.print');

    Route::get('/hubunganKeluarga', 'SuratKeteranganHubunganKeluargaController@indexGuest')->name('hubunganKeluarga.index');
    Route::post('/hubunganKeluarga', 'SuratKeteranganHubunganKeluargaController@insertGuest')->name('hubunganKeluarga.insert');
    Route::get('/hubunganKeluarga/print/{id}', 'SuratKeteranganHubunganKeluargaController@print')->name('hubunganKeluarga.print');

    Route::get('/PanggilanCerai', 'SuratKeteranganPanggilanCeraiController@indexGuest')->name('PanggilanCerai.index');
    Route::post('/PanggilanCerai', 'SuratKeteranganPanggilanCeraiController@insertGuest')->name('PanggilanCerai.insert');
    Route::get('/PanggilanCerai/print/{id}', 'SuratKeteranganPanggilanCeraiController@print')->name('PanggilanCerai.print');

    Route::get('/keterangan', 'SuratKeteranganController@indexGuest')->name('keterangan.index');
    Route::post('/keterangan', 'SuratKeteranganController@insertGuest')->name('keterangan.insert');
    Route::get('/keterangan/print/{id}', 'SuratKeteranganController@print')->name('keterangan.print');

    Route::get('/keteranganKematian', 'SuratKeteranganTentangKematianController@indexGuest')->name('keteranganKematian.index');
    Route::post('/keteranganKematian', 'SuratKeteranganTentangKematianController@insertGuest')->name('keteranganKematian.insert');
    Route::get('/keteranganKematian/print/{id}', 'SuratKeteranganTentangKematianController@print')->name('keteranganKematian.print');

    Route::get('/keteranganKelahiran', 'SuratKeteranganKelahiranController@indexGuest')->name('keteranganKelahiran.index');
    Route::post('/keteranganKelahiran', 'SuratKeteranganKelahiranController@insertGuest')->name('keteranganKelahiran.insert');
    Route::get('/keteranganKelahiran/print/{id}', 'SuratKeteranganKelahiranController@print')->name('keteranganKelahiran.print');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home.index');
Route::get('/about', 'AboutController@index')->name('about.index');
Route::get('/dashboard/{name?}', 'DashboardController@index' )->name('dashboard.index');


Route::resource('preferences', 'PreferenceController')->only(['index', 'store']);
Route::patch('preferences/logo/update', 'PreferenceController@updateLogo')->name('preferences.update.logo');
Route::delete('preferences/logo/destroy', 'PreferenceController@destroyLogo')->name('preferences.destroy.logo');

Route::resource('users', 'UserController');
Route::patch('users/{user}/password/update', 'UserController@updatePassword')->name('users.update.password');

Route::resource('suratKeteranganDomisilis', 'SuratKeteranganDomisiliController');

Route::resource('suratKeteranganIzinKeramaians', 'SuratKeteranganIzinKeramaianController');

Route::resource('suratKeteranganPajaks', 'SuratKeteranganPajakController');

Route::resource('suratKeteranganPenghasilans', 'SuratKeteranganPenghasilanController');

Route::get('documents', 'DocumentController@index')->name('documents.index');


Route::resource('suratRekomendasiImbs', 'SuratRekomendasiImbController');

Route::resource('suratKeteranganUsahas', 'SuratKeteranganUsahaController');

Route::resource('suratKuasaTanahs', 'SuratKuasaTanahController');

Route::resource('suratKeteranganTidakMampus', 'SuratKeteranganTidakMampuController');

Route::resource('suratKeteranganAhliWaris', 'SuratKeteranganAhliWarisController');

Route::resource('ahliWarisKeterenganAhliWaris', 'AhliWarisKeterenganAhliWarisController');

Route::resource('saksiKeteranganAhliWaris', 'SaksiKeteranganAhliWarisController');

Route::resource('suratKeteranganBedaNamas', 'SuratKeteranganBedaNamaController');

Route::resource('suratKeteranganBelumNpwps', 'SuratKeteranganBelumNpwpController');

Route::resource('suratPernyataanHibahs', 'SuratPernyataanHibahController');

Route::resource('riwayatKepemilikanHibahs', 'RiwayatKepemilikanHibahController');

Route::resource('suratKeteranganJandas', 'SuratKeteranganJandaController');

Route::resource('suratBelumPernahMenikahs', 'SuratBelumPernahMenikahController');

Route::resource('suratKeteranganHubunganKeluargas', 'SuratKeteranganHubunganKeluargaController');

Route::resource('suratKeteranganPanggilanCerais', 'SuratKeteranganPanggilanCeraiController');

Route::resource('suratKeterangans', 'SuratKeteranganController');

Route::resource('suratKeteranganTentangKematians', 'SuratKeteranganTentangKematianController');

Route::resource('suratKeteranganKelahirans', 'SuratKeteranganKelahiranController');

app/Http/Controllers/SuratKeteranganJandaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateSuratKeteranganJandaRequest;
use App\Http\Requests\UpdateSuratKeteranganJandaRequest;
use App\Repositories\SuratKeteranganJandaRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

use App\Models\SuratKeteranganJanda;
use App\Models\Status;
use App\Models\Preference;
use Carbon\Carbon;
use App\Http\Requests\SuratKeteranganJandaRequest;

class SuratKeteranganJandaController extends AppBaseController
{
    /** @var  SuratKeteranganJandaRepository */
    private $suratKeteranganJandaRepository;

    public function __construct(SuratKeteranganJandaRepository $suratKeteranganJandaRepo)
    {
        $this->suratKeteranganJandaRepository = $suratKeteranganJandaRepo;
        $this->middleware('auth');
    }

    /**
     * Display a listing of the SuratKeteranganJanda.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $suratKeteranganJandas = $this->suratKeteranganJandaRepository->all();

        return view('surat_keterangan_jandas.index')
            ->with('suratKeteranganJandas', $suratKeteranganJandas);
    }

    /**
     * Show the form for creating a new SuratKeteranganJanda.
     *
     * @return Response
     */
    public function create()
    {
        return view('surat_keterangan_jandas.create');
    }

    /**
     * Store a newly created SuratKeteranganJanda in storage.
     *
     * @param CreateSuratKeteranganJandaRequest $request
     *
     * @return Response
     */
    public function store(CreateSuratKeteranganJandaRequest $request)
    {
        $input   = $request->all();
        $dateNow = Carbon::now()->format('Y-m-d');
        $status  = Status::where('status','draf')->first();

        $input['user_id']           = auth()->user()->id;
        $input['status_id']         = $status->id;
        $input['tanggal_pengajuan'] = $dateNow;

        $suratKeteranganJanda = $this->suratKeteranganJandaRepository->create($input);

        Flash::success('Surat Keterangan Janda saved successfully.');

        return redirect(route('suratKeteranganJandas.index'));
    }

    /**
     * Display the specified SuratKeteranganJanda.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $suratKeteranganJanda = $this->suratKeteranganJandaRepository->find($id);

        if (empty($suratKeteranganJanda)) {
            Flash::error('Surat Keterangan Janda not found');

            return redirect(route('suratKeteranganJandas.index'));
        }

        return view('surat_keterangan_jandas.show')->with('suratKeteranganJanda', $suratKeteranganJanda);
    }

    /**
     * Show the form for editing the specified SuratKeteranganJanda.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $suratKeteranganJanda = $this->suratKeteranganJandaRepository->find($id);

        if (empty($suratKeteranganJanda)) {
            Flash::error('Surat Keterangan Janda not found');

            return redirect(route('suratKeteranganJandas.index'));
        }

        return view('surat_keterangan_jandas.edit')->with('suratKeteranganJanda', $suratKeteranganJanda);
    }

    /**
     * Update the specified SuratKeteranganJanda in storage.
     *
     * @param int $id
     * @param UpdateSuratKeteranganJandaRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateSuratKeteranganJandaRequest $request)
    {
        $suratKeteranganJanda = $this->suratKeteranganJandaRepository->find($id);

        if (empty($suratKeteranganJanda)) {
            Flash::error('Surat Keterangan Janda not found');

            return redirect(route('suratKeteranganJandas.index'));
        }

        $allRequestData          = $request->all();

        if($request->terima == 'Terima'){
            $status  = Status::where('status','Diterima')->first();
            $dateNow = Carbon::now()->format('Y-m-d');

            $countSurat = SuratKeteranganJanda::whereNotNull('nomor_surat')->count();
            $nomorSurat = str_pad(($countSurat+1), 4, 0,STR_PAD_LEFT);

            $allRequestData['status_id'] = $status->id;
            if($suratKeteranganJanda->tanggal_terbit == NULL && $suratKeteranganJanda->nomor_surat == NULL){
                $allRequestData['tanggal_terbit'] = $dateNow;
                $allRequestData['nomor_surat']    = "882/ $nomorSurat /I/ PEM";
            }
            
            $suratKeteranganJanda = $this->suratKeteranganJandaRepository->update($allRequestData, $id);

            return redirect()->back()->with('status','print_surat');
        }else{
            $status       = Status::where('status','Ditolak')->first();

            $allRequestData['status_id'] = $status->id;

            $suratKeteranganJanda = $this->suratKeteranganJandaRepository->update($allRequestData, $id);

            Flash::success('Surat Keterangan Janda updated successfully.');

            return redirect(route('suratKeteranganJandas.index'));
        }
    }

    /**
     * Remove the specified SuratKeteranganJanda from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $suratKeteranganJanda = $this->suratKeteranganJandaRepository->find($id);

        if (empty($suratKeteranganJanda)) {
            Flash::error('Surat Keterangan Janda not found');

            return redirect(route('suratKeteranganJandas.index'));
        }

        $this->suratKeteranganJandaRepository->delete($id);

        Flash::success('Surat Keterangan Janda deleted successfully.');

        return redirect(route('suratKeteranganJandas.index'));
    }

    public function print($id)
    {
        $suratKeteranganJanda = SuratKeteranganJanda::find($id);
        $preferences          = Preference::get()->keyBy('label')->toArray();
        $dateNow              = Carbon::now()->format('d-m-Y');
        $pdf                  = \PDF::loadView('khusus.suratKeteranganJanda.surat', ['suratKeteranganJanda' => $suratKeteranganJanda,'preferences' => $preferences, 'dateNow' => $dateNow]);
        return $pdf->stream('surat.pdf',array("Attachment" => 0));
    }

    public function indexGuest()
    {
        return view('khusus.suratKeteranganJanda.index');
    }

    public function insertGuest(SuratKeteranganJandaRequest $request)
    {
        $status  = Status::where('status','draf')->first();
        $user    = auth()->user();
        $dateNow = Carbon::now();

        $suratKeteranganJanda                    = new SuratKeteranganJanda;
        $suratKeteranganJanda->user_id           = $user->id;
        $suratKeteranganJanda->nik               = $request->nik;
        $suratKeteranganJanda->nama              = $request->nama;
        $suratKeteranganJanda->jenis_kelamin     = $request->jenis_kelamin;
        $suratKeteranganJanda->tempat_lahir      = $request->tempat_lahir;
        $suratKeteranganJanda->tgl_lahir         = $request->tgl_lahir;
        $suratKeteranganJanda->status_perkawinan = $request->status_perkawinan;
        $suratKeteranganJanda->kewarganegaraan   = $request->kewarganegaraan;
        $suratKeteranganJanda->agama             = $request->agama;
        $suratKeteranganJanda->pekerjaan         = $request->pekerjaan;
        $suratKeteranganJanda->alamat            = $request->alamat;
        $suratKeteranganJanda->rt                = $request->rt;
        $suratKeteranganJanda->rw                = $request->rw;
        $suratKeteranganJanda->sebab_cerai       = $request->sebab_cerai;
        $suratKeteranganJanda->administrasi      = $request->administrasi;
        $suratKeteranganJanda->status_id         = $status->id;
        $suratKeteranganJanda->tanggal_pengajuan = $dateNow->format('Y-m-d');
        $suratKeteranganJanda->save();

        $hariKadarluasaPengajuan = $dateNow->addDays(2)->format('Y-m-d');
        return view('khusus.suratKeteranganJanda.kodeSurat')->with([
            'suratKeteranganJanda'    => $suratKeteranganJanda,
            'hariKadarluasaPengajuan' => $hariKadarluasaPengajuan
            ]);
    }
}

resources/views/surat_keterangan_jandas/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Surat Keterangan Janda
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'suratKeteranganJandas.store']) !!}

                        @include('surat_keterangan_jandas.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/surat_keterangan_jandas/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Surat Keterangan Janda
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($suratKeteranganJanda, ['route' => ['suratKeteranganJandas.update', $suratKeteranganJanda->id], 'method' => 'patch']) !!}

                        @include('surat_keterangan_jandas.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/surat_keterangan_jandas/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Surat Keterangan Janda</h1>
    </section>
    <div class="clearfix"></div>
    <br>
    <div class="col-sm-4">
        <a class="btn btn-primary" href="{{ route('suratKeteranganJandas.create') }}">
            Pengajuan Surat Keterangan Janda Baru
        </a>
    </div>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                <div class="col-sm-12">
                    @include('surat_keterangan_jandas.table')
                </div>
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/surat_keterangan_jandas/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Surat Keterangan Janda
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('surat_keterangan_jandas.show_fields')
                    <a href="{{ route('suratKeteranganJandas.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/surat_keterangan_jandas/show_fields.blade.php
<!-- User Id Field -->
<div class="form-group">
    {!! Form::label('user_id', 'User Id:') !!}
    <p>{{ $suratKeteranganJanda->user_id }}</p>
</div>

<!-- Nik Field -->
<div class="form-group">
    {!! Form::label('nik', 'Nik:') !!}
    <p>{{ $suratKeteranganJanda->nik }}</p>
</div>

<!-- Nama Field -->
<div class="form-group">
    {!! Form::label('nama', 'Nama:') !!}
    <p>{{ $suratKeteranganJanda->nama }}</p>
</div>

<!-- Jenis Kelamin Field -->
<div class="form-group">
    {!! Form::label('jenis_kelamin', 'Jenis Kelamin:') !!}
    <p>{{ $suratKeteranganJanda->jenis_kelamin }}</p>
</div>

<!-- Tempat Lahir Field -->
<div class="form-group">
    {!! Form::label('tempat_lahir', 'Tempat Lahir:') !!}
    <p>{{ $suratKeteranganJanda->tempat_lahir }}</p>
</div>

<!-- Tgl Lahir Field -->
<div class="form-group">
    {!! Form::label('tgl_lahir', 'Tgl Lahir:') !!}
    <p>{{ $suratKeteranganJanda->tgl_lahir }}</p>
</div>

<!-- Status Field -->
<div class="form-group">
    {!! Form::label('status', 'Status:') !!}
    <p>{{ $suratKeteranganJanda->status }}</p>
</div>

<!-- Kewarganegaraan Field -->
<div class="form-group">
    {!! Form::label('kewarganegaraan', 'Kewarganegaraan:') !!}
    <p>{{ $suratKeteranganJanda->kewarganegaraan }}</p>
</div>

<!-- Agama Field -->
<div class="form-group">
    {!! Form::label('agama', 'Agama:') !!}
    <p>{{ $suratKeteranganJanda->agama }}</p>
</div>

<!-- Pekerjaan Field -->
<div class="form-group">
    {!! Form::label('pekerjaan', 'Pekerjaan:') !!}
    <p>{{ $suratKeteranganJanda->pekerjaan }}</p>
</div>

<!-- Alamat Field -->
<div class="form-group">
    {!! Form::label('alamat', 'Alamat:') !!}
    <p>{{ $suratKeteranganJanda->alamat }}</p>
</div>

<!-- Rt Field -->
<div class="form-group">
    {!! Form::label('rt', 'Rt:') !!}
    <p>{{ $suratKeteranganJanda->rt }}</p>
</div>

<!-- Rw Field -->
<div class="form-group">
    {!! Form::label('rw', 'Rw:') !!}
    <p>{{ $suratKeteranganJanda->rw }}</p>
</div>

<!-- Sebab Cerai Field -->
<div class="form-group">
    {!! Form::label('sebab_cerai', 'Sebab Cerai:') !!}
    <p>{{ $suratKeteranganJanda->sebab_cerai }}</p>
</div>

<!-- Administrasi Field -->
<div class="form-group">
    {!! Form::label('administrasi', 'Administrasi:') !!}
    <p>{{ $suratKeteranganJanda->administrasi }}</p>
</div>

<!-- Status Id Field -->
<div class="form-group">
    {!! Form::label('status_id', 'Status Id:') !!}
    <p>{{ $suratKeteranganJanda->status_id }}</p>
</div>

<!-- Tanggal Pengajuan Field -->
<div class="form-group">
    {!! Form::label('tanggal_pengajuan', 'Tanggal Pengajuan:') !!}
    <p>{{ $suratKeteranganJanda->tanggal_pengajuan }}</p>
</div>

<!-- Tanggal Terbit Field -->
<div class="form-group">
    {!! Form::label('tanggal_terbit', 'Tanggal Terbit:') !!}
    <p>{{ $suratKeteranganJanda->tanggal_terbit }}</p>
</div>

<!-- Nomor Surat Field -->
<div class="form-group">
    {!! Form::label('nomor_surat', 'Nomor Surat:') !!}
    <p>{{ $suratKeteranganJanda->nomor_surat }}</p>
</div>

resources/views/surat_keterangan_jandas/table.blade.php
@section( 'scripts' )
@include( 'layouts.datatables_js' )

<script type="text/javascript">
    $( document ).ready( function() {
        $( '#suratKeteranganJandas-table' ).DataTable({

        });
    } );
</script>
@endsection
<div class="table-responsive">
    <table class="table" id="suratKeteranganJandas-table">
        <thead>
            <tr>
                <th>Nik</th>
                <th>Nama</th>
                <th>Jenis Kelamin</th>
                <th>Tempat Lahir</th>
                <th>Tgl Lahir</th>
                <th>Status Perkawinan</th>
                <th>Kewarganegaraan</th>
                <th>Agama</th>
                <th>Pekerjaan</th>
                <th>Alamat</th>
                <th>Rt</th>
                <th>Rw</th>
                <th>Sebab Cerai</th>
                <th>Administrasi</th>
                <th>Status Surat</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($suratKeteranganJandas as $suratKeteranganJanda)
            <tr>
                <td>{{ $suratKeteranganJanda->nik }}</td>
                <td>{{ $suratKeteranganJanda->nama }}</td>
                <td>{{ $suratKeteranganJanda->jenis_kelamin }}</td>
                <td>{{ $suratKeteranganJanda->tempat_lahir }}</td>
                <td>{{ $suratKeteranganJanda->tgl_lahir }}</td>
                <td>{{ $suratKeteranganJanda->status_perkawinan }}</td>
                <td>{{ $suratKeteranganJanda->kewarganegaraan }}</td>
                <td>{{ $suratKeteranganJanda->agama }}</td>
                <td>{{ $suratKeteranganJanda->pekerjaan }}</td>
                <td>{{ $suratKeteranganJanda->alamat }}</td>
                <td>{{ $suratKeteranganJanda->rt }}</td>
                <td>{{ $suratKeteranganJanda->rw }}</td>
                <td>{{ $suratKeteranganJanda->sebab_cerai }}</td>
                <td>{{ $suratKeteranganJanda->administrasi }}</td>
                <td>{{ $suratKeteranganJanda->status->status }}</td>
                <td>
                    {!! Form::open(['route' => ['suratKeteranganJandas.destroy', $suratKeteranganJanda->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('suratKeteranganJandas.edit', [$suratKeteranganJanda->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>